export const AGREGAR_PRODUCTO='AGREGRAR_PRODUCTO';
export const AGREGAR_PRODUCTO_EXITO='AGREGAR_PRODUCTO_EXITO';
export const AGREGAR_PRODUCTO_ERROR='AGREGAR_PRODUCTO_ERROR';

export const INICIAR_CONSULTAR_PRODUCTOS="INICIAR_CONSULTAR_PRODUCTOS";
export const CONSULTAR_PRODUCTOS_EXITO="INICIAR_CONSULTAR_EXITO";
export const CONSULTAR_PRODUCTOS_ERROR="CONSULTAR_PRODUCTOS_ERROR";

export const OBTENER_PRODUCTO_ELIMINAR='OBTENER_PRODUCTO_ELIMINAR';
export const PRODUCTO_ELIMINADO='PRODUCTO_ELIMINADO';
export const PRODUCTO_NOELIMINADO='PRODUCTO_NOELIMINADO';
